# Generated by Django 3.1 on 2021-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='employee',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='employee_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
    ]
