# Generated by Django 3.1 on 2021-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210608_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
