# Generated by Django 3.2.4 on 2021-06-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
