# Generated by Django 3.2.4 on 2021-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_users_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(default=0)),
                ('employee', models.CharField(default=0, max_length=50)),
                ('job_id', models.IntegerField(default=0)),
                ('job', models.CharField(default=0, max_length=50)),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
