# Generated by Django 3.2.4 on 2021-06-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='job',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='job_id',
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
