# Generated by Django 3.1 on 2021-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210610_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_weekly',
            field=models.IntegerField(default=0),
        ),
    ]
