# Generated by Django 3.2.4 on 2021-06-15 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210615_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='car_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='leaving_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='national_insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='pension',
            field=models.IntegerField(default=0),
        ),
    ]
