# Generated by Django 3.1 on 2021-06-16 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_crud'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
