# Generated by Django 3.2.4 on 2021-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_employeelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default=0, max_length=70)),
                ('job', models.CharField(default=0, max_length=70)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
